---
kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: python:3.7-slim
  commands:
  - pip install .
  - pip install -r requirements.txt
  - pytest

- name: build docs
  image: python:3.7-slim
  commands:
  - pip install . pdoc3
  - rm -rf ./docs/ai/
  - pdoc3 ./ai --html -o docs

- name: push
  image: alpine/git
  environment:
    KEY:
      from_secret: PRIVATEKEY
  commands:
  - mkdir $HOME/.ssh
  - echo "$KEY" > $HOME/.ssh/id_rsa
  - git add docs
  - git config user.name drone
  - git config user.email drone
  - git commit -m "[CI SKIP]" --allow-empty
  - git push origin master

trigger:
  branch:
  - master
  event:
  - push
